package model.vo;

import oracle.jbo.CriteriaClauses;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 20 16:37:52 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EDRemittanceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EDRemittanceVOImpl() {
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public Number getp_org_id() {
        return (Number)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(Number value) {
        setNamedWhereClauseParam("p_org_id", value);
    }

    /**
     * Returns the bind variable value for p_header_id.
     * @return bind variable value for p_header_id
     */
    public Number getp_header_id() {
        return (Number)getNamedWhereClauseParam("p_header_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_header_id.
     * @param value value to bind as p_header_id
     */
    public void setp_header_id(Number value) {
        setNamedWhereClauseParam("p_header_id", value);
    }
  
}
