package model.lov;

import model.generic.GenericLovClass;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 20 16:50:37 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BankNamesLOVImpl extends GenericLovClass {
    /**
     * This is the default constructor (do not remove).
     */
    public BankNamesLOVImpl() {
    }

    /**
     * Returns the bind variable value for p_receipt_method_id.
     * @return bind variable value for p_receipt_method_id
     */
    public String getp_receipt_method_id() {
        return (String)getNamedWhereClauseParam("p_receipt_method_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_receipt_method_id.
     * @param value value to bind as p_receipt_method_id
     */
    public void setp_receipt_method_id(String value) {
        setNamedWhereClauseParam("p_receipt_method_id", value);
    }
}
