package model.lov;

import model.generic.GenericLovClass;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 20 16:58:08 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExchangeTypesLOVImpl extends GenericLovClass {
    /**
     * This is the default constructor (do not remove).
     */
    public ExchangeTypesLOVImpl() {
    }
}
