package model.lov;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 25 20:04:00 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExchangeRateLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExchangeRateLOVImpl() {
    }

    /**
     * Returns the bind variable value for p_from_currency.
     * @return bind variable value for p_from_currency
     */
    public String getp_from_currency() {
        return (String)getNamedWhereClauseParam("p_from_currency");
    }

    /**
     * Sets <code>value</code> for bind variable p_from_currency.
     * @param value value to bind as p_from_currency
     */
    public void setp_from_currency(String value) {
        setNamedWhereClauseParam("p_from_currency", value);
    }

    /**
     * Returns the bind variable value for gl_date.
     * @return bind variable value for gl_date
     */
    public Date getgl_date() {
        return (Date)getNamedWhereClauseParam("gl_date");
    }

    /**
     * Sets <code>value</code> for bind variable gl_date.
     * @param value value to bind as gl_date
     */
    public void setgl_date(Date value) {
        setNamedWhereClauseParam("gl_date", value);
    }
}
