package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 17 17:34:35 PKT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String callCreateReceiptProc(int sqlReturnType, String stmt);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);
}
